site_name: Wally Packages
site_url: https://alexasterisk.github.io/WallyPackages/

markdown_extensions:
  - meta
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.highlight

theme:
  name: material
  palette:
    primary: blue
    accent: cyan
    scheme: slate
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.tabs

nav:
  - Home: index.md
  - Import:
    - Introduction: import/index.md
    - Installation: import/installation.md
    - Usage: import/usage.md
  - Logger:
    - Introduction: logger/index.md
    - Usage: logger/usage.md
  - PlayerResolvable:
    - Introduction: playerResolvable/index.md
  - TableUtil:
    - Introduction: table-util/index.md
  - LuaObjects:
    - Introduction: objects/index.md
  - Tween:
    - Introduction: tween/index.md