[package]
name = "alexinite/arrays-maps-sets"
description = "Introduces Arrays, Maps, and Sets from TypeScript"
version = "0.1.5"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
TableUtil = "alexinite/table-util@0.1.1"