[package]
name = "alexinite/lua-class"
description = "A module that finally implements classes like JS/TS's Classes"
version = "0.1.1"
authors = ["Alexinite"]
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
exclude = ["README.md", "wally.lock"]
realm = "shared"