[package]
name = "alexinite/player-resolvable"
description = "A simple resolver for getting Players, usernames, characters, and user ids from any of the previous."
version = "0.2.0"
authors = ["alexasterisk"]
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
exclude = ["README.md", "wally.lock"]
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"