[package]
name = "alexinite/tween"
description = "An extension to Roblox's built-in TweenService."
version = "0.1.0"
authors = ["alexasterisk"]
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
exclude = ["README.md", "wally.lock"]
realm = "shared"