[package]
name = "alexinite/lua-array"
description = "Adds Arrays from TypeScript into Luau with almost* full implementation"
version = "0.1.0"
authors = ["Alexinite"]
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
LuaClass = "alexinite/lua-class@0.1.2"